version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk:341.0.0-slim
    volumes:
      - gcp-creds:/creds
      - .:/src
    working_dir: /src
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds: